### ISSUE TITLE
能不能自动加载原图

### ISSUE THREAD

**Issue by vividmuse** [kihlh/WxDatViewerAutoExportRust#16]
挨个点好麻烦  
不点就只保存缩略图

**Comment by kihlh** [comment]
在2.0中强制
默认启用同步和保存原图
2.0预计在最近一周发布
![image](https://github.com/kihlh/WxDatViewerAutoExportRust/assets/62889891/04dcf8c9-cb3d-4a43-ac92-c862c3700dd7)

**Comment by kihlh** [comment]
同时也支持保留上次配置信息
![image](https://github.com/kihlh/WxDatViewerAutoExportRust/assets/62889891/6d86d1b3-676c-462a-891b-0e7185caec4e)

**Comment by vividmuse** [comment]
> 同时也支持保留上次配置信息 ![image](https://user-images.githubusercontent.com/62889891/276477542-6d86d1b3-676c-462a-891b-0e7185caec4e.png)

1.0貌似不能修改现有配置 如果支持修改就更好了

**Comment by kihlh** [comment]
1.0已经不再维护了，2.0代码更新量超过70%，无法用来凑合使用在1.0了

你可以按照默认值添加，然后直接编辑数据库文件，数据库是一个SQL life 文件，使用db 浏览器就可以直接编辑

或者您可以等待2.0发布

**Comment by kihlh** [comment]
2.0版本已发布
