### ISSUE TITLE
能不能支持文件

### ISSUE THREAD

**Issue by GANLAN1314** [kihlh/WxDatViewerAutoExportRust#24]
实际上群聊中的文件是最难受的，因为聊天和图片都发在队列里，一段时间没有参与聊天就会积累大量无用的信息和文件，微信里选择了自动下载依旧会漏掉很多文件，导致每次查找文件得到的结果都是文件已被清理，这样每个微信群就必须专人每个星期将所有文件下载一遍，不然就会一直丢文件，太烦了

**Comment by kihlh** [comment]
这个需要hook和对程序进行修改才能做到，所以并不能做到，而且这是很危险的行为
