### ISSUE TITLE
请问计划支持mac吗？

### ISSUE THREAD

**Issue by yzy-lex** [kihlh/WxDatViewerAutoExportRust#28]
请问计划支持mac吗？

**Comment by kihlh** [comment]
隔行如隔山，开发mac版本需要有mac或者黑苹果，以我的财力很难做得到，而且mac软件需要证书签名，此软件开发了两个多月一共就收到了不到50的捐赠，五十分之一证书的钱都不够

所以很抱歉，无法考虑多平台兼容
如果有人想维护第三方平台我会提供支持的

**Comment by yzy-lex** [comment]
好滴 谢谢
