### ISSUE TITLE
得空整个使用说明吧

### ISSUE THREAD

**Issue by sayhi987** [kihlh/WxDatViewerAutoExportRust#29]
建议增加个使用使用说明文档

不知道是否支持多任务，同时监控多个群和微信好友的聊天图片。
谢谢！

**Comment by kihlh** [comment]
任务可以无限个创建

**Comment by kihlh** [comment]
除了每天一次的全量扫描任务是单线程全量的，

实时更新是支持所有任务同时检查变化的

**Comment by kihlh** [comment]
因为网上太多文档了 所以我就懒得写了，相比起1.0已经简单很多了，你下载的应该是吾爱破解版，开源版致谢那边有教程链接

https://mp.weixin.qq.com/s/GZgURnMUxmD0yMkyoFCOPw
