### ISSUE TITLE
支持文件导出的命名选项

### ISSUE THREAD

**Issue by kihlh** [kihlh/WxDatViewerAutoExportRust#3]
文件夹变量: ·`月`  `天`  `周` 
文件名变量：`%NN序列`    `创建日期`    `时`    `分`    `日`    `月`    `dat名称`

%NN序列   :  （自增序列号  如果NN 不足两位数补足到两位数 0 会被转义为 00  ， NNN 就是 000）
- **举个栗子 移除类推**
-  %N= `0`    `1`   `2`   `10`   `11`   `15`   `100`
-  %NN= `00`    `01`   `02`   `10`   `11`   `15`   `100`
-   %NNN= `000`    `001`   `002`   `010`   `011`   `015`   `100`

变量格式：`月` \ `创建日期` _ [ ``%NN`` ]
支持预览：05\2023-01-05[05].jpg

**Comment by kihlh** [comment]
![image](https://github.com/kihlh/WxDatViewerAutoExportRust/assets/62889891/0196c2b1-7cd3-4bf0-b83e-4b2d07e65a55)

**Comment by mariahlamb31** [comment]
气气 不更更 骗骗
![1795](https://github.com/kihlh/WxDatViewerAutoExportRust/assets/117580900/0909beac-4faa-498a-a617-9d2b96144bae)
