### ISSUE TITLE
没法读取早期图片记录吗

### ISSUE THREAD

**Issue by weedi0** [kihlh/WxDatViewerAutoExportRust#30]
扫描有6000多记录，但是实际只能提取到2500条左右，文件是存在的，在微信里可以复制另存。查看导出的图片最早到22年6月。再早的都没有

**Comment by kihlh** [comment]
这部分没有被分类 无法获取到对应的聊天对象， 全导出太多没用的了

**Comment by kihlh** [comment]
微信支持分组也是最近一年的事

**Comment by kihlh** [comment]
> 扫描有6000多记录，但是实际只能提取到2500条左右，文件是存在的，在微信里可以复制另存。查看导出的图片最早到22年6月。再早的都没有

这三千多很有可能只是 缩略图 而设置默认不启用缩略图

**Comment by weedi0** [comment]
不是缩略图，应该是分组读取方式的问题。
