### ISSUE TITLE
希望增加命名规则

### ISSUE THREAD

**Issue by magic-up** [kihlh/WxDatViewerAutoExportRust#38]
在寻找自动下载微信图片的方法，看到作者的项目很是开心！👍👍👍
1.增加<发送者>，以便后期的图片分类整理，进一步方便对于微信群聊图片的后期整理。
2.增加<微信图片的发送时间（不同于下载时间）>，以便可以按照接收的时间排序与分类。

**Comment by kihlh** [comment]
1,2都有

**Comment by kihlh** [comment]
功能请求1：
![image](https://github.com/user-attachments/assets/3224d064-d159-4298-8e62-f87b6b04607c)
功能请求2：
![image](https://github.com/user-attachments/assets/5f59de5f-1d8b-4fcb-83c3-5047a844093c)

**Comment by kihlh** [comment]
至于自动下载实现是非常困难的，方法基本都是侵入式的
1.读取数据库
2.读取内存
3.模拟人工

我现在选择实现3  功能详见https://github.com/kihlh/WxDatViewerAutoExportRust/issues/39

**Comment by magic-up** [comment]
很感谢你的回复，你好，这个创建时间可以更加精确些吗，精确到分钟

**Comment by magic-up** [comment]
然后功能1中我是希望下载一个群聊的图片，里面会有多个人发送，想针对群聊的情况进一步区分发送者

**Comment by kihlh** [comment]
> 很感谢你的回复，你好，这个创建时间可以更加精确些吗，精确到分钟

他可以精确到分，但是不支持群聊内进一步区分人员因为这事侵入式的请求

**Comment by magic-up** [comment]
好的，谢谢。可以问一下我应该怎么做可以使得标记创建时间到分，我点击<时><分>显示的是下载时间的时与分

**Comment by magic-up** [comment]
作者，你好。我的描述有些偏差，对于命名的时间我希望是所下载的图片本身在微信中发送方发送这个图片的时间，而非下载这个图片的时间

**Comment by kihlh** [comment]
以后再考虑吧，我现在在思考如何实现自动读取原图

**Comment by magic-up** [comment]
嗯嗯，好的
